[project]
name = "options-ensemble-bot"
version = "0.1.0"
description = "Options ensemble bot"
requires-python = ">=3.12"

[tool.black]
line-length = 88

[tool.ruff]
line-length = 88

[tool.mypy]
python_version = "3.12"
